# Generated by Django 5.1.2 on 2024-10-31 11:14

import django.db.models.deletion
import tests.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer_a', models.TextField()),
                ('answer_b', models.TextField()),
                ('answer_c', models.TextField()),
                ('answer_d', models.TextField()),
                ('correct_answer', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1)),
                ('score', models.IntegerField(default=2)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.set')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=uuid.uuid4, max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('passed_score', models.IntegerField()),
                ('questions_count', models.IntegerField(default=120)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('not_started', 'Boshlanmagan'), ('passed', "O'tgan"), ('failed', 'Yiqilgan'), ('ended', 'Tugagan')], default='not_started', max_length=20, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True)),
                ('elapsed', models.IntegerField(blank=True, default=0, null=True)),
                ('cases', models.JSONField(blank=True, default=tests.models.json, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('questions', models.ManyToManyField(blank=True, null=True, related_name='test_questions', to='tests.question')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.set')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
