# Generated by Django 5.1.2 on 2024-12-14 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_alter_test_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='left',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='no_person',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='right',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='two_person',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
