# Generated by Django 5.1.2 on 2024-12-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_test_left_test_no_person_test_right_test_two_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='left',
            new_name='attention',
        ),
        migrations.RemoveField(
            model_name='test',
            name='right',
        ),
        migrations.AddField(
            model_name='test',
            name='fine',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='on_blur',
            field=models.IntegerField(default=0),
        ),
    ]
