# Generated by Django 5.1.2 on 2024-12-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_rename_left_test_attention_remove_test_right_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='attention',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='no_person',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='two_person',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
